apiVersion: apps/v1 
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels: 
        app: client
    spec:
      containers:
        - name: client
          image: oliverafajardo/client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

# ClusterIP is a type of service that exposes the service on a private IP address inside the cluster
#eveng bus is listening on port 4005, so we will map that port to the service


